input:
    output_dir_base: "/home/sarapc/Desktop/MID_QC/ComparisonDataMC_A02D" #to be modify manually
    
    period: "PbPb2024"  # period: to be modify manually
    pass: "apass1"      # pass: to be modify manually
    
    output_dir_name: "/home/sarapc/Desktop/MID_QC/ComparisonDataMC_A02D/PbPb2024_apass1"  #output_dir_base/periodo_pass

    #List of runs: to be modify manually (can be taken from the dataset - Note that in the dataset the runs are ordered in increasing order )
    run_list_MC: [
     560012,559987,559970,559969,559968,559966,559933,559920,559919,559917,559903,559902,559901,559856,559843,559830,559828,559827,559804,559803,559802,559784,559783,559782,559781,559762,559749,559731,559713,559681,559680,559679,559632,559631,559617,559616,559615,559614,559613,559596,559595,559575,559574,559561,559545,559544
    ]

    #Path from Hyperoop: to be modify manually (can be taken from the submitted jobs page - Note that in the submitted jobs page the runs and the output_directory are ordered in decresing order )
    alien_input_path: [
       "/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487571","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487570","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487569","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487568","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487567","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487566","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487565","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487564","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487563","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487562","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487561","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487560","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487559","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487558","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487557","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487556","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487555","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487554","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487553","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487552","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487551","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487550","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487549","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487548","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487547","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487546","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487544","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487543","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487542","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487541","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487540","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487539","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487538","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487537","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487536","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487535","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487534","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487533","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487532","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487531","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487530","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487529","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487528","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487527","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487526","/alice/cern.ch/user/a/alihyperloop/jobs/0148/hy_1487525"
    ]

    file_type: "AnalysisResults.root"

    #Needed for the merge part of the script
#    file_path: "/media/luca/Extreme SSD/MIDefficieincy/LHC22o_pass7_minBias/runs"
#    table_maker_stat: table-maker/Statistics
#    table_maker: table-maker/output
#    table_maker_dir: ["Muons_muonQualityCuts"]
#    table_maker_obj: ["Pt"]

#Needed for the merge part of the script
#output:
#    output_fig_name: figures_1/LHC22o_full_stat
#    output_dir_name: output_1/Data
#    output_file_name: LHC22q_apass3_muons.root













