input:
    output_dir_base: "/home/sarapc/Desktop/MID_QC/ComparisonDataMC_A02D" #to be modify manually
    
    period: "PbPb2023"  # period: to be modify manually
    pass: "apass4"      # pass: to be modify manually
    
    output_dir_name: "/home/sarapc/Desktop/MID_QC/ComparisonDataMC_A02D/ppref_apass1_2024"  #output_dir_base/periodo_pass

    #List of runs: to be modify manually
    run_list_data: [
        559456,559444,559443,559437,559423,559410,559409,559408,559387,559385,559362,559361,559348
    ]

    #Path from Hyperoop: to be modify manually
    alien_input_path: [
        "/alice/cern.ch/user/a/alihyperloop/jobs/0140/hy_1403411","/alice/cern.ch/user/a/alihyperloop/jobs/0140/hy_1403402","/alice/cern.ch/user/a/alihyperloop/jobs/0140/hy_1403401","/alice/cern.ch/user/a/alihyperloop/jobs/0140/hy_1403400","/alice/cern.ch/user/a/alihyperloop/jobs/0140/hy_1403380","/alice/cern.ch/user/a/alihyperloop/jobs/0140/hy_1403379","/alice/cern.ch/user/a/alihyperloop/jobs/0140/hy_1403378","/alice/cern.ch/user/a/alihyperloop/jobs/0140/hy_1403376","/alice/cern.ch/user/a/alihyperloop/jobs/0140/hy_1403369","/alice/cern.ch/user/a/alihyperloop/jobs/0140/hy_1403368","/alice/cern.ch/user/a/alihyperloop/jobs/0140/hy_1403349","/alice/cern.ch/user/a/alihyperloop/jobs/0140/hy_1403346","/alice/cern.ch/user/a/alihyperloop/jobs/0140/hy_1403341"
    ]

    file_type: "AnalysisResults.root"

    #Needed for the merge part of the script
#    file_path: "/media/luca/Extreme SSD/MIDefficieincy/LHC22o_pass7_minBias/runs"
#    table_maker_stat: table-maker/Statistics
#    table_maker: table-maker/output
#    table_maker_dir: ["Muons_muonQualityCuts"]
#    table_maker_obj: ["Pt"]

#Needed for the merge part of the script
#output:
#    output_fig_name: figures_1/LHC22o_full_stat
#    output_dir_name: output_1/Data
#    output_file_name: LHC22q_apass3_muons.root
